// Generated by IcedCoffeeScript 1.8.0-c
var __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; };

define(['trakio/lodash'], function(_) {
  var Identify;
  return Identify = (function() {
    function Identify() {
      this.map_properties = __bind(this.map_properties, this);
      this.distinct_id = __bind(this.distinct_id, this);
      this.should_identify = __bind(this.should_identify, this);
      this.event_fired = __bind(this.event_fired, this);
      this.page_ready = __bind(this.page_ready, this);
      this.initialize = __bind(this.initialize, this);
    }

    Identify.prototype.initialize = function(automagic, options) {
      this.automagic = automagic;
      this.options = options;
    };

    Identify.prototype.page_ready = function() {};

    Identify.prototype.event_fired = function(element, event, callback, automagic_ready) {
      var e;
      try {
        if (_.matches(element, this.options.selector) && this.options.should_identify.call(this.automagic, element, event)) {
          trak.io.identify(this.distinct_id(element), this.map_properties(element), function() {
            automagic_ready.identify = true;
            return callback();
          });
        }
      } catch (_error) {
        e = _error;
        trak.io.debug_error(e);
      }
      automagic_ready.identify = true;
      return callback();
    };

    Identify.prototype.should_identify = function(element, event) {
      var has_all, has_any, properties;
      properties = this.map_properties(element);
      has_any = _.filter(properties, (function(_this) {
        return function(value, key) {
          return _.contains(_this.options.has_any_fields, key);
        };
      })(this)).length > 0;
      has_all = _.filter(properties, (function(_this) {
        return function(value, key) {
          return _.contains(_this.options.has_all_fields, key);
        };
      })(this)).length >= this.options.has_all_fields.length;
      return has_any && has_all;
    };

    Identify.prototype.distinct_id = function(element) {
      var index, key, property, r, value, _ref;
      r = {};
      _ref = this.map_properties(element);
      for (property in _ref) {
        value = _ref[property];
        if ((index = _.indexOf(this.options.distinct_ids, property)) > -1) {
          r[index] = value;
        }
      }
      for (key in r) {
        value = r[key];
        if (value && value !== "") {
          return value;
        }
      }
      return trak.io.distinct_id();
    };

    Identify.prototype.map_properties = function(form) {
      var field, input, inputs, name, property, r, value, _i, _len, _ref;
      inputs = _.find("input", form);
      r = {};
      for (_i = 0, _len = inputs.length; _i < _len; _i++) {
        input = inputs[_i];
        if (!_.matches(input, this.options.excluded_field_selector)) {
          name = _.attr(input, 'name');
          _ref = this.options.property_map;
          for (property in _ref) {
            field = _ref[property];
            if (typeof field === 'string' && field === name || typeof field.test === 'function' && field.test(name)) {
              value = input.value;
              if (value && value !== "") {
                r[property] = value;
              }
              break;
            }
          }
        }
      }
      return r;
    };

    return Identify;

  })();
});
