// Generated by IcedCoffeeScript 1.7.1-b
describe('Trak', function() {
  var Exceptions;
  Exceptions = null;
  before(function(done) {
    sinon.stub(trak.io, 'track');
    sinon.stub(trak.io, 'url').returns('page_url');
    sinon.stub(trak.io, 'page_title').returns('A page title');
    sinon.stub(trak.io, 'should_track').returns(true);
    return requirejs(['exceptions'], function(E) {
      Exceptions = E;
      return done();
    });
  });
  after(function() {
    trak.io.track.restore();
    trak.io.page_title.restore();
    trak.io.url.restore();
    return trak.io.should_track.restore();
  });
  describe('#page_view()', function() {
    return it("should call #track", function() {
      trak.io.page_view();
      return trak.io.track.should.have.been.calledWith('page_view', {
        url: 'page_url',
        page_title: 'A page title'
      });
    });
  });
  describe('#page_view(url)', function() {
    return it("should call #track", function() {
      trak.io.page_view('custom_page_url');
      return trak.io.track.should.have.been.calledWith('page_view', {
        url: 'custom_page_url',
        page_title: 'A page title'
      });
    });
  });
  return describe('#page_view(url, title)', function() {
    return it("should call #track", function() {
      trak.io.page_view('custom_page_url', 'custom page title');
      return trak.io.track.should.have.been.calledWith('page_view', {
        url: 'custom_page_url',
        page_title: 'custom page title'
      });
    });
  });
});
