// Generated by IcedCoffeeScript 1.7.1-b
var __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

define(['exception'], function(Exception) {
  var MissingParameter;
  return MissingParameter = (function(_super) {
    __extends(MissingParameter, _super);

    function MissingParameter() {
      return MissingParameter.__super__.constructor.apply(this, arguments);
    }

    return MissingParameter;

  })(Exception);
});
