// Generated by IcedCoffeeScript 1.4.0c
var __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

define(['exception'], function(Exception) {
  var PropertiesObjectInvalid;
  return PropertiesObjectInvalid = (function(_super) {

    __extends(PropertiesObjectInvalid, _super);

    function PropertiesObjectInvalid() {
      return PropertiesObjectInvalid.__super__.constructor.apply(this, arguments);
    }

    return PropertiesObjectInvalid;

  })(Exception);
});
