// Generated by IcedCoffeeScript 1.4.0c

define(['exception'], function(Exception) {
  var Unknown;
  return Unknown = (function() {

    function Unknown(message, code, details, data) {
      this.message = message;
      this.code = code;
      this.details = details;
      this.data = data;
    }

    return Unknown;

  })();
});
