// Generated by IcedCoffeeScript 1.8.0-c
var __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

define(function() {
  var Exception;
  return Exception = (function(_super) {
    __extends(Exception, _super);

    function Exception(message, code, details, data) {
      this.message = message;
      this.code = code;
      this.details = details;
      this.data = data;
    }

    return Exception;

  })(Error);
});
