// Generated by IcedCoffeeScript 1.4.0c

require(['trak', 'lodash', 'cookie'], function(Trak, _, cookie) {
  var item, method, queue, trak;
  trak = new Trak();
  queue = window.trak;
  window.trak = trak;
  while (queue && queue.length > 0) {
    item = queue.shift();
    method = item.shift();
    if (trak.io[method]) trak.io[method].apply(trak.io, item);
  }
  cookie.defaults.expires = 3650;
  cookie.defaults.path = '/';
  return window.cookie = cookie;
});
