// Generated by IcedCoffeeScript 1.8.0-c
define(['sizzle', 'lodash', 'trakio/lodash/events'], function(Sizzle, _, events) {
  _.find = function(selector, context) {
    if (context == null) {
      context = null;
    }
    return Sizzle(selector, context);
  };
  _.matches = function(element, selector) {
    return Sizzle.matchesSelector(element, selector);
  };
  _.attr = function(element, attribute, value) {
    if (value == null) {
      value = false;
    }
    if (element) {
      if (value) {
        return element.setAttribute(attribute, value);
      } else {
        return element.getAttribute(attribute);
      }
    }
  };
  _.merge(_, events);
  return _;
});
